src/Entity/Tournament.php
<?php

namespace App\Entity;

use App\Entity\League;
use App\Entity\Stadium;
use App\Entity\Inscription;
use Doctrine\ORM\Mapping as ORM;
use App\Repository\TournamentRepository;
use Doctrine\Common\Collections\Collection;
use Doctrine\Common\Collections\ArrayCollection;

/**
 * @ORM\Entity(repositoryClass=TournamentRepository::class)
 */
class Tournament
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\ManyToOne(targetEntity=League::class, inversedBy="tournaments")
     * @ORM\JoinColumn(nullable=false)
     */
    private $league;

    /**
     * @ORM\ManyToOne(targetEntity=Stadium::class, inversedBy="tournaments")
     * @ORM\JoinColumn(nullable=false)
     */
    private $stadium;

    /**
     * @ORM\Column(type="datetime")
     */
    private $start_date;

    /**
     * @ORM\Column(type="datetime")
     */
    private $end_date;

    /**
     * @ORM\Column(type="integer")
     */
    private $nbMaxTeam;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $description;

    /**
     * @ORM\Column(type="string", length=20, nullable=true)
     */
    private $ageCategory;

    /**
     * @ORM\OneToMany(targetEntity=Inscription::class, mappedBy="tournament", orphanRemoval=true)
     */
    private $inscriptions;

    /**
     * @ORM\Column(type="string", length=60)
     */
    private $title;

    public function __construct()
    {
        $this->inscriptions = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getLeague(): ?League
    {
        return $this->league;
    }

    public function setLeague(?League $league): self
    {
        $this->league = $league;

        return $this;
    }

    public function getStadium(): ?Stadium
    {
        return $this->stadium;
    }

    public function setStadium(?Stadium $stadium): self
    {
        $this->stadium = $stadium;

        return $this;
    }

    public function getStartDate(): ?\DateTimeInterface
    {
        return $this->start_date;
    }

    public function setStartDate(\DateTimeInterface $start_date): self
    {
        $this->start_date = $start_date;

        return $this;
    }

    public function getEndDate(): ?\DateTimeInterface
    {
        return $this->end_date;
    }

    public function setEndDate(\DateTimeInterface $end_date): self
    {
        $this->end_date = $end_date;

        return $this;
    }

    public function getNbMaxTeam(): ?int
    {
        return $this->nbMaxTeam;
    }

    public function setNbMaxTeam(int $nbMaxTeam): self
    {
        $this->nbMaxTeam = $nbMaxTeam;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(?string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getAgeCategory(): ?string
    {
        return $this->ageCategory;
    }

    public function setAgeCategory(?string $ageCategory): self
    {
        $this->ageCategory = $ageCategory;

        return $this;
    }

    /**
     * @return Collection|Inscription[]
     */
    public function getInscriptions(): Collection
    {
        return $this->inscriptions;
    }

    public function addInscription(Inscription $inscription): self
    {
        if (!$this->inscriptions->contains($inscription)) {
            $this->inscriptions[] = $inscription;
            $inscription->setTournament($this);
        }

        return $this;
    }

    public function removeInscription(Inscription $inscription): self
    {
        if ($this->inscriptions->removeElement($inscription)) {
            // set the owning side to null (unless already changed)
            if ($inscription->getTournament() === $this) {
                $inscription->setTournament(null);
            }
        }

        return $this;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }
}

src/Form/TournamentType.php
<?php

namespace App\Form;

use DateTime;
use App\Entity\Stadium;
use App\Entity\Tournament;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\DateType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\Extension\Core\Type\NumberType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;

class TournamentType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('title', TextType::class,[
                'label' => 'Titre'
            ])
            ->add('description', TextareaType::class,[
                'label' => 'Description',
                'required' => false
            ])
            ->add('start_date', DateType::class,[
                'label' => 'Date de début',
                'years' => range(date('Y'), date('Y')+20),
                'required' => true
            ])
            ->add('end_date', DateType::class,[
                'label' => 'Date de Fin',
                'years' => range(date('Y'), date('Y')+20),
                'required' => true
            ])
            ->add('nbMaxTeam', NumberType::class,[
                'attr' => [
                    "min" => 2,
                    "max" => 64
                ],
                "html5" => true,
                "scale" => 0,
                'label' => 'Nombre maximum d\'équipes autorisées'
            ])
            ->add('ageCategory', ChoiceType::class,[
                'label' => 'Catégorie d\'Age',
                'choices' => [
                    'Poussins' => 'poussins',
                    'Benjamins' => 'benjamains',
                    'Cadets' => 'cadets',
                    'Juniors' => 'juniors',
                    'Seniors' => 'seniors',
                    'Vétérans' => 'vétérans'
                ],
                'required' => false
            ])
            ->add('stadium', EntityType::class, [
                'class' => Stadium::class,
                'choice_label' => 'name',
                'label' => 'Stade'
            ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Tournament::class,
        ]);
    }
}

src/Controller/TournamentController.php
<?php

namespace App\Controller;

use App\Entity\Tournament;
use App\Form\TournamentType;
use App\Repository\InscriptionRepository;
use App\Repository\UserRepository;
use App\Repository\LeagueRepository;
use App\Repository\TournamentRepository;
use Doctrine\ORM\EntityManagerInterface;
use Knp\Component\Pager\PaginatorInterface;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Security;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;

/**
 * @Route("/tournament")
 */
class TournamentController extends AbstractController
{
    private EntityManagerInterface $entityManager;

    public function __construct(EntityManagerInterface $manager)
    {
        $this->entityManager = $manager;
    }

    /**
     * @Route("/", name="tournament_index", methods={"GET"})
     */
    public function index(Request $request, TournamentRepository $tournamentRepository, UserRepository $userRepository, PaginatorInterface $paginator): Response
    {
        // Tournois sortis par date de début de la plus proche à la plus lointaine
        $donnees = $tournamentRepository->findBy(
            [],
            ['start_date' => 'ASC']
        );

        // Pagination
        $tournaments = $paginator->paginate(
            $donnees, // on passe les données, ici les tournois
            $request->query->getInt('page', 1), // Numéro de la page en cours, 1 par défaut
            8
        );

        return $this->render('tournament/index.html.twig', [
            'tournaments' => $tournaments,
            'users' => $userRepository->getUsersWithLeague()
        ]);
    } 

    /**
     * @Route("/new", name="tournament_new", methods={"GET","POST"})
     * @Security("is_granted('ROLE_USER') and user in userRepository.getUsersWithLeague()", statusCode=403, message="Accès interdit")
     */
    public function new(Request $request, UserRepository $userRepository, LeagueRepository $leagueRepository): Response
    {
        $tournament = new Tournament();
        $form = $this->createForm(TournamentType::class, $tournament);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $tournament->setLeague($leagueRepository->findOneBy(['responsible' => $this->getUser()]));
            $this->entityManager->persist($tournament);
            $this->entityManager->flush();

            $this->addFlash(
                "success",
                "Le Tournoi a bien été ajouté"
            );

            return $this->redirectToRoute('tournament_index');
        }

        return $this->render('tournament/new.html.twig', [
            'tournament' => $tournament,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="tournament_show", methods={"GET"})
     */
    public function show(Tournament $tournament, InscriptionRepository $inscriptionRepository): Response
    {
        $clubsInscrits = [];
        $inscriptions = $inscriptionRepository->findBy(['tournament' => $tournament]);
        foreach($inscriptions as $inscription){
            array_push($clubsInscrits, $inscription->getClub());
        }

        return $this->render('tournament/show.html.twig', [
            'tournament' => $tournament,
            'clubsInscrits' => $clubsInscrits
        ]);
    }

    /**
     * @Route("/{id}/edit", name="tournament_edit", methods={"GET","POST"})
     * @Security("is_granted('ROLE_ADMIN') or tournament.getLeague().getResponsible() == user")
     */
    public function edit(Request $request, Tournament $tournament): Response
    {
        $form = $this->createForm(TournamentType::class, $tournament);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->entityManager->flush();

            $this->addFlash(
                "success",
                "Mise à jour effectuée avec succès"
            );

            return $this->redirectToRoute('tournament_index');
        }

        return $this->render('tournament/edit.html.twig', [
            'tournament' => $tournament,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="tournament_delete", methods={"DELETE"})
     */
    public function delete(Request $request, Tournament $tournament): Response
    {
        if ($this->isCsrfTokenValid('delete'.$tournament->getId(), $request->request->get('_token'))) {
            $this->entityManager->remove($tournament);
            $this->entityManager->flush();

            $this->addFlash(
                "success",
                "Suppression réussie"
            );
        }

        return $this->redirectToRoute('tournament_index');
    }
}

templates/tournament/_delete_form.html.twig
<form method="post" action="{{ path('tournament_delete', {'id': tournament.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');" class="mt-1">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ tournament.id) }}">
    <button class="btn btn-danger">Supprimer</button>
</form>

templates/tournament/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn btn-success mt-1">{{ button_label|default('Enregistrer') }}</button>
{{ form_end(form) }}

templates/tournament/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Tournament{% endblock %}

{% block body %}
    <h1>Edit Tournament</h1>

    {{ include('tournament/_form.html.twig', {'button_label': 'Mettre à jour'}) }}

    <a class="btn btn-outline-primary mt-1" href="{{ path('tournament_index') }}">Liste des tournois</a>

    {{ include('tournament/_delete_form.html.twig') }}
{% endblock %}

templates/tournament/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Tournament index{% endblock %}

{% block body %}
    <div class="container-fluid">
        <h1>Les Tournois</h1>

        {% if is_granted("ROLE_USER") and (app.user in users) %}
            <a class="btn btn-outline-success m-2" href="{{ path('tournament_new') }}">Ajouter un tournoi</a>
        {% endif %}

        <div class="row align-items-center justify-content-around">
        {% for tournament in tournaments %}
            <div class="card mt-4">
                <div class="card-body">
                    <h5 class="card-title">{{ tournament.title }}</h5>
                    <p class="card-text">
                        Ce tournoi est se déroule au
                        <a class="card-link" href="{{ path('stadium_show', { 'id': tournament.stadium.id}) }}">{{ tournament.stadium.name }}</a>
                    </p>
                    <p class="card-text">
                        Ce tournoi est organisé par la <br/>
                        <a class="card-link" href="{{ path('league_show', { 'id': tournament.league.id}) }}">{{ tournament.league.name }}</a>
                    </p>
                    <p class="card-text">
                        Catégorie : {{ tournament.ageCategory|capitalize }}
                    <p>
                    <p>
                        Date de début du tournoi : 
                        <span>{{ tournament.startDate ? tournament.startDate|date('d-m-Y') : '' }}</span>
                    </p>
                    <p>
                        Places restantes : <span class="text-info font-weight-bold">{{ tournament.nbMaxTeam - tournament.inscriptions|length }}</span> / {{ tournament.nbMaxTeam }}

                    </p>
                    <a href="{{ path('tournament_show', {'id': tournament.id}) }}" class="btn btn-outline-info mt-2">Voir plus</a>
                    {% if app.user is same as(tournament.league.responsible) %}
                        <a href="{{ path('tournament_edit', {'id': tournament.id}) }}" class="btn btn-outline-secondary mt-2">Modifier</a>
                    {% endif %}
                </div>
            </div>
        {% else %}
            <p>
                Aucun tournoi trouvé
            </p>
        {% endfor %}
        </div>
        <div class="d-flex justify-content-center">
            {{ knp_pagination_render(tournaments) }}
        </div>
    </div>

{% endblock %}

templates/tournament/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Tournament{% endblock %}

{% block body %}
    <h1>Create new Tournament</h1>

    {{ include('tournament/_form.html.twig') }}

    <a class="btn btn-outline-primary" href="{{ path('tournament_index') }}">Liste des tournois</a>
{% endblock %}

templates/tournament/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Tournament{% endblock %}

{% block body %}
<div class="card border-0 justify-content-center align-items-center">
        {% if app.user.club is not null and app.user.club not in clubsInscrits %}
            <form class="mt-2 w-100" method="POST" action="{{ path('inscription_new', { 'tournamentId': tournament.id, 'clubId': app.user.club.id }) }}">
                <button type="submit" class="btn btn-success w-100">
                    S'Inscrire à ce Tournoi
                </button>
            </form>
        {% endif %}
        <div class="card-body">
            <h1 class="card-title">{{ tournament.title }}</h1>
            <p class="card-text">
                {{ tournament.description }}
            </p>
            <p class="card-text">
                Nombre maximum d'équipes autorisées : <span class="text-info font-weight-bold">{{ tournament.nbMaxTeam }}</span>
            </p>
            
            <p class="card-text">
                Date de début du tournoi : 
                <span>{{ tournament.startDate ? tournament.startDate|date('d M Y') : '' }}</span>
            </p>
            <p class="card-text">
                Date de fin du tournoi :
                <span>{{ tournament.endDate ? tournament.endDate|date('d M Y') : '' }}</span>
            </p>
            <p class="card-text">
                Ce tournoi est se déroule au
                <a class="card-link" href="{{ path('stadium_show', { 'id': tournament.stadium.id}) }}">{{ tournament.stadium.name }}</a>
            </p>
            <p class="card-text">
                Ce tournoi est organisé par la
                <a class="card-link" href="{{ path('league_show', { 'id': tournament.league.id}) }}">{{ tournament.league.name }}</a>
            </p>
            <p class="card-text">
                Catégorie : {{ tournament.ageCategory | capitalize }}
            <p>
            <div class="card justify-content-center">
                <h2 class="card-header">Clubs participants</h2>
                {% for inscription in tournament.inscriptions %}
                    <p>
                        <a class="card-link" href="{{ path('club_show',{ 'id': inscription.club.id }) }}" >{{ inscription.club.name }}</a>
                    </p>
                {% else %}
                    <p> Aucun club n'est inscrit à ce tournoi</p>
                {% endfor %}
            </div>

        </div>
    </div>

    <a class="btn btn-outline-primary mt-1" href="{{ path('tournament_index') }}">Liste des tournois</a>

    {% if app.user is same as(tournament.league.responsible) %}
        <a class="btn btn-outline-secondary mt-1" href="{{ path('tournament_edit', {'id': tournament.id}) }}">Modifier</a>
        {{ include('tournament/_delete_form.html.twig') }}
    {% endif %}

{% endblock %}